"""
recovery_agent.py
─────────────────
GPT-4o + code_interpreter agent for Under-Specification (US) mutations.

The agent's job is to recover the PROMPT — not to generate the final code.

GPT-4o uses its code interpreter sandbox to test hypotheses about what
constraint was silently removed from the mutated prompt.  It writes candidate
code, runs it against the inline examples (>>> docstring examples for
HumanEval, or any context available), and uses the results to determine
the missing constraint.  Once confident, it returns a restored prompt with
the constraint added back.

The local model then generates the final code from the restored prompt.

Flow per sample:

  mutated US prompt
        │
        ▼
  GPT-4o + code_interpreter:
        ├─ hypothesises missing constraint
        ├─ writes test code, runs against inline examples
        ├─ revises hypothesis until examples pass
        └─ returns RESTORED PROMPT (constraint added back)
                │
                ▼
        local model → code from restored prompt
                │
                ▼
        run real hidden tests → result

Usage:
    from recovery_agent import RecoveryAgent
    agent  = RecoveryAgent(pipeline, model="gpt-4o")
    result = agent.recover(mutated_prompt, row=row, kind="humaneval", entry_point=ep)
    print(result["fixed_prompt"])
    print(result["passed"])
"""

from __future__ import annotations

import re
from typing import Optional

from openai import OpenAI


# ── Prompts ────────────────────────────────────────────────────────────────────

# Step 1: GPT-4o + code_interpreter — explore and identify the missing constraint
_EXPLORE_SYSTEM = """\
You are an expert at diagnosing under-specified programming prompts.
A prompt has had one constraint silently removed.
Use the code interpreter to test hypotheses: write small snippets, run them
against the inline examples (>>> lines) in the prompt, and determine what
constraint is missing.  If no examples are present, reason from the function
signature and context.
At the end, state clearly in plain text: what the missing constraint is."""

_EXPLORE_USER = """\
The following programming prompt is missing exactly one constraint.
Use the code interpreter to investigate, then tell me what constraint was removed.

Mutated prompt:
{prompt}"""

# Step 2: plain chat.completions — produce the restored prompt
_RESTORE_SYSTEM = """\
You are a technical writer repairing a programming challenge prompt.
You will be given the mutated prompt and the identified missing constraint.
Reintegrate the constraint naturally into the prompt.
Rules:
- Keep the function signature, existing examples, and structure intact.
- Only add the missing constraint — change nothing else.
Return ONLY the restored prompt text, no explanation."""

_RESTORE_USER = """\
Mutated prompt:
{prompt}

Missing constraint identified: {constraint}

Return the restored prompt with the constraint naturally added back:"""


# ── Helpers ────────────────────────────────────────────────────────────────────

def _collect_text(response) -> str:
    """Concatenate all text output items from a Responses API response."""
    parts = []
    for item in response.output:
        if hasattr(item, "content"):
            for block in item.content:
                if hasattr(block, "text"):
                    parts.append(block.text)
        elif hasattr(item, "text"):
            parts.append(item.text)
    return "\n".join(parts)


# ── Agent ──────────────────────────────────────────────────────────────────────

class RecoveryAgent:
    """
    GPT-4o + code_interpreter agent for US-mutated prompts.

    Returns a restored prompt; the local model generates the final code.
    """

    def __init__(
        self,
        pipeline,
        openai_client: Optional[OpenAI] = None,
        model:         str              = "gpt-4o",
        max_tokens:    int              = 4096,
    ):
        self.pipeline   = pipeline
        self.client     = openai_client or OpenAI()
        self.model      = model
        self.max_tokens = max_tokens

    def recover(
        self,
        prompt:      str,
        row:         dict,
        kind:        str,
        entry_point: Optional[str] = None,
    ) -> dict:
        """
        Returns:
            fixed_prompt  – restored prompt with missing constraint added back
                            (falls back to original mutated prompt on failure)
            code          – code generated by local model from fixed_prompt
            passed        – True if code passes real hidden tests
            raw_response  – full GPT-4o response text
        """
        from eval_fixer import run_eval
        from inference_pipeline import (
            build_lora_instruction,
            extract_code_block,
            extract_func_name,
        )

        # ── Step 1: GPT-4o + code_interpreter identifies the missing constraint ──
        explore_resp = self.client.responses.create(
            model             = self.model,
            tools             = [{"type": "code_interpreter", "container": {"type": "auto"}}],
            input             = [
                {"role": "system", "content": _EXPLORE_SYSTEM},
                {"role": "user",   "content": _EXPLORE_USER.format(prompt=prompt)},
            ],
            max_output_tokens = self.max_tokens,
        )
        constraint = _collect_text(explore_resp).strip()
        print(f"    [agent] constraint identified ({len(constraint)} chars)")

        # ── Step 2: plain chat.completions rewrites the prompt ────────────────
        restore_resp = self.client.chat.completions.create(
            model       = self.model,
            messages    = [
                {"role": "system", "content": _RESTORE_SYSTEM},
                {"role": "user",   "content": _RESTORE_USER.format(
                    prompt=prompt, constraint=constraint)},
            ],
            temperature = 0.1,
        )
        fixed_prompt = restore_resp.choices[0].message.content.strip()

        if not fixed_prompt:
            print("    [agent] WARNING: empty restored prompt, using mutated prompt")
            fixed_prompt = prompt

        print(f"    [agent] prompt restored ({len(fixed_prompt)} chars)")

        # ── Local model generates code from restored prompt ────────────────────
        ep          = entry_point or extract_func_name(fixed_prompt)
        instruction = build_lora_instruction(fixed_prompt, ep)
        raw_code    = self.pipeline._generate(instruction, use_lora=False)
        code        = extract_code_block(raw_code)

        passed = run_eval(code, row, kind)
        print(f"    [agent] real tests: {'✓' if passed else '✗'}")

        return {
            "fixed_prompt": fixed_prompt,
            "code":         code,
            "passed":       passed,
            "raw_response": constraint,
        }
